### PR TITLE
Add forbidden term

### PR DESCRIPTION
**Pull request by mattleff**
Refs discussion at https://github.com/bountonw/translate/pull/276/files/db6fb6e572160425fa2d66c50f8cf3e40a94ed43#diff-032ed34b9bb29513827777c0ba6497f265c4a9111701f30ccb3bad6c29701b67.

### CODE REVIEW

**Comment by bountonw** [comment]
I am wondering if this is ever legit. Is there a way of searching the available Thai bibles if it occurs with the galan?

**Comment by mattleff** [comment]
Good question... Let me see if I can figure that out.

**Comment by bountonw** [comment]
I commented on the PR. Both spellings are legit depending on the Bible version. I prefer spelling it with the galan unless quoting a version that doesn't use it.

**Comment by mattleff** [comment]
Looks pretty consistent: TNCV seems to always use the galan; TH1971 never does. I haven't found a place with this phrase in THSV11 yet.

**Pull request closed without merging**
